### ISSUE TITLE
Activar la camara sin https desde javascript.

### ISSUE THREAD

**Issue by aegislp** [UNLP-IADM/secretmsg#2]
Hola gente

Puede ser que si no tenes activado HTTPS desde el servidor chrome no te permite acceder a la camara desde javascript?

**Comment by dpaez** [comment]
Hola @aegislp. Desde localhost no tendrías que tener problemas para acceder a recursos como la cámara. 

En otros ambientes hay que usar HTTPS para acceder a estos recursos.
